# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/PC/Desktop/PERSO/expense_tracker_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/PC/Desktop/PERSO/expense_tracker_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/PC/Desktop/PERSO/expense_tracker_cpp/CMakeFiles C:/Users/PC/Desktop/PERSO/expense_tracker_cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/PC/Desktop/PERSO/expense_tracker_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EXPENSE_TRACKER_CPP

# Build rule for target.
EXPENSE_TRACKER_CPP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EXPENSE_TRACKER_CPP
.PHONY : EXPENSE_TRACKER_CPP

# fast build rule for target.
EXPENSE_TRACKER_CPP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/build
.PHONY : EXPENSE_TRACKER_CPP/fast

src/balance.obj: src/balance.cpp.obj
.PHONY : src/balance.obj

# target to build an object file
src/balance.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/balance.cpp.obj
.PHONY : src/balance.cpp.obj

src/balance.i: src/balance.cpp.i
.PHONY : src/balance.i

# target to preprocess a source file
src/balance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/balance.cpp.i
.PHONY : src/balance.cpp.i

src/balance.s: src/balance.cpp.s
.PHONY : src/balance.s

# target to generate assembly for a file
src/balance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/balance.cpp.s
.PHONY : src/balance.cpp.s

src/habit.obj: src/habit.cpp.obj
.PHONY : src/habit.obj

# target to build an object file
src/habit.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/habit.cpp.obj
.PHONY : src/habit.cpp.obj

src/habit.i: src/habit.cpp.i
.PHONY : src/habit.i

# target to preprocess a source file
src/habit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/habit.cpp.i
.PHONY : src/habit.cpp.i

src/habit.s: src/habit.cpp.s
.PHONY : src/habit.s

# target to generate assembly for a file
src/habit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/habit.cpp.s
.PHONY : src/habit.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/user.obj: src/user.cpp.obj
.PHONY : src/user.obj

# target to build an object file
src/user.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/user.cpp.obj
.PHONY : src/user.cpp.obj

src/user.i: src/user.cpp.i
.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s
.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EXPENSE_TRACKER_CPP.dir/build.make CMakeFiles/EXPENSE_TRACKER_CPP.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EXPENSE_TRACKER_CPP"
	@echo "... src/balance.obj"
	@echo "... src/balance.i"
	@echo "... src/balance.s"
	@echo "... src/habit.obj"
	@echo "... src/habit.i"
	@echo "... src/habit.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/user.obj"
	@echo "... src/user.i"
	@echo "... src/user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

